name: Qameta Documentation
description: Documentation for Qameta tools

url: https://qameta.io

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: pretty

gems:
  - jekyll-redirect-from

collections:
  allure:
    output: true
