name: Qameta Documentation
description: Documentation for Qameta tools
url: https://docs.qameta.io

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: pretty

sass:
  style: compressed

gems:
  - jekyll-redirect-from
  - jekyll-asciidoc