name: Qameta Documentation
description: Documentation for Qameta tools
url: https://docs.qameta.io

markdown: kramdown
kramdown:
  input: GFM
  eanble_coderay: true
  syntax_highlighter: coderay
  syntax_highlighter_opts:
    coderay_line_numbers: nil

permalink: pretty

sass:
  style: compressed

gems:
  - jekyll-redirect-from
  - jekyll-asciidoc