= jUnit
:icons: font
:imagesdir: /allure/1.4/img/
:page-layout: docs
:page-version: 1.4
:page-product: allure
:source-highlighter: coderay

WARNING: Allure only supports JUnit 4. You will get nothing with JUnit 3.

== Installation

=== Maven

You need to add the following to your *pom.xml*:
[source, xml]
.pom.xml
----
...
<properties>
    <aspectj.version>1.7.4</aspectj.version>
    <allure.version>{latest-allure-version}</allure.version>
</properties>

<dependencies>
    <dependency>
        <groupId>ru.yandex.qatools.allure</groupId>
        <artifactId>allure-junit-adaptor</artifactId>
        <version>${allure.version}</version>
    </dependency>
</dependencies>

<build>
    <plugins>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-surefire-plugin</artifactId>
            <version>2.14</version>
            <configuration>
                <testFailureIgnore>false</testFailureIgnore>
                <argLine>
                    -javaagent:${settings.localRepository}/org/aspectj/aspectjweaver/${aspectj.version}/aspectjweaver-${aspectj.version}.jar
                </argLine>
                <properties>
                    <property>
                        <name>listener</name>
                        <value>ru.yandex.qatools.allure.junit.AllureRunListener</value>
                    </property>
                </properties>
            </configuration>
            <dependencies>
                <dependency>
                    <groupId>org.aspectj</groupId>
                    <artifactId>aspectjweaver</artifactId>
                    <version>${aspectj.version}</version>
                </dependency>
            </dependencies>
        </plugin>
    </plugins>
</build>
...
----

Then run the build as usual:

[source, bash]
----
$ mvn clean test
----

== Features

This adapter comes with a set of Java annotations and traits allowing to use main Allure features.

=== Title
In order to add such title to any test class or https://github.com/allure-framework/allure-core/wiki/Glossary#test-case[test case]
method you need to annotate it with *@Title* annotation:

[source, java]
----
package my.company.tests;

import org.junit.Test;
import ru.yandex.qatools.allure.annotations.Title;

@Title("Human-readable test suite title")
public class SearchTest {

    @Test
    @Title("Human-readable test case title")
    public void searchTest() throws Exception {
        ...
    }

}
----

=== Description
Similarly you can add detailed description for each test class and
https://github.com/allure-framework/allure-core/wiki/Glossary#test-case[test method].

To add such description simply use *@Description* annotation:

[source, java]
----
@Description(value = "Detailed description for this <b>test suite</b>.", type = DescriptionType.HTML)
public class SearchTest {

    @Test
    @Description(value = "Detailed description for this *test case*.", type = DescriptionType.MARKDOWN)
    public void searchTest() throws Exception {

    }

}
----

Description can be added in plain text, HTML or Markdown format - simply assign different **type** value.


=== Steps

Steps are any actions that constitute a testing scenario. Steps can be used in different testing scenarios.
They can: be parametrized, make checks, have nested steps, and create attachments. Each step has a name.

In order to define steps in Java code, you need to annotate the respective methods with **@Step** annotation.
When not specified, the step name is equal to the annotated method name converted to human-readable format.
To define an explicit step name:

[source, java]
----
@Step("Open {0} page.")
public void openPageByAddress(String pageAddress) {
     ...
}
----

Step names support the following placeholders:

* *{N}* where N is a zero-based positive integer that will be replaced by the Nth method argument value (0 corresponds
  to the first argument, 1 to the second, etc.). See example above.
* *{method}* will be replaced by the annotated method name e.g. *openPageByAddress*


Depending on the project layout, you can consider adding Allure dependency to the test scope only.

== Ant

Right now using Allure with http://ant.apache.org[Ant] is not possible,
because the http://junit.sourceforge.net/javadoc/org/junit/runner/notification/RunListener.html[RunListener] that we
provide is only supported in JUnit 4, whereas even the latest version of Ant requires the implementation of JUnit 3 specific interfaces.